package com.linternapremium.app.localization

import android.content.Context
import androidx.core.content.edit
import java.util.Locale

enum class AppLanguage(val code: String, val nativeLabel: String) {
    SPANISH("es", "Español"),
    ENGLISH("en", "English"),
    PORTUGUESE("pt", "Português"),
    FRENCH("fr", "Français"),
    ITALIAN("it", "Italiano"),
    GERMAN("de", "Deutsch"),
    RUSSIAN("ru", "Русский"),
    JAPANESE("ja", "日本語"),
    CHINESE("zh", "简体中文");

    companion object {
        fun fromCode(code: String?): AppLanguage = entries.firstOrNull {
            it.code == code?.substringBefore('-')?.lowercase(Locale.ROOT)
        } ?: SPANISH
    }
}

enum class TextKey {
    LANGUAGES,
    APP_LANGUAGE,
    PREMIUM_ACTIVE,
    PLEBEIAN_EDITION,
    READY_TO_LIGHT,
    MAX_INTENSITY_HELP,
    TURN_ON,
    RESET_PLEBEIAN,
    RESET_HELP,
    PREMIUM_OFF_PROGRESS,
    TORCH_ON_MAX,
    TORCH_ALREADY_OFF,
    CELEBRATION_HELP,
    CHOOSE_ELEGANCE,
    COMPLETE_OR_RETURN,
    NORMAL_PLEBEIAN_OFF,
    BACK,
    PREMIUM_OFF,
    ALREADY_YOURS,
    FIVE_STAR_DARKNESS,
    FIREWORKS_A11Y,
    LOCAL_TEST,
    PRICE_GOOGLE_PLAY,
    ONE_TIME_NO_SUBSCRIPTION,
    DEMO_PURCHASE_HELP,
    PLAY_PURCHASE_HELP,
    SIMULATE_PURCHASE,
    CONTINUE_PLAY,
    NOT_NOW,
    FLASHLIGHT_ICON,
    TEST_AD,
    CAMERA_PERMISSION,
    NORMAL_OFF_NOTICE,
    PREMIUM_OFF_NOTICE,
    DEMO_PREMIUM_ACTIVATED,
    DEMO_PREMIUM_RESET,
    PREMIUM_ACTIVATED,
    TORCH_NO_FLASH,
    TORCH_ACCESS_ERROR,
    TORCH_BUSY,
    TORCH_UNAVAILABLE,
    BILLING_NOT_READY,
    PRODUCT_UNAVAILABLE,
    INVALID_OFFER,
    OPEN_PAYMENT_ERROR,
    PURCHASE_CANCELLED,
    PURCHASE_FAILED,
    PAYMENT_PENDING,
    PAYMENT_ACK_FAILED,
    BILLING_NOT_CONFIGURED,
}

class LinternaText internal constructor(
    val language: AppLanguage,
    private val values: Map<TextKey, String>,
) {
    operator fun get(key: TextKey): String = values.getValue(key)
}

object LinternaTextCatalog {
    val supportedLanguages: List<AppLanguage> = AppLanguage.entries

    fun forLanguage(language: AppLanguage): LinternaText =
        LinternaText(language, catalogs.getValue(language))

    fun missingKeys(language: AppLanguage): Set<TextKey> =
        TextKey.entries.toSet() - catalogs.getValue(language).keys

    private val catalogs: Map<AppLanguage, Map<TextKey, String>> = mapOf(
        AppLanguage.SPANISH to catalog(
            "Idiomas", "Idioma de la aplicación", "PREMIUM ACTIVO", "EDICIÓN PLEBEYA",
            "Lista para iluminar", "Usaremos la mayor intensidad que permita tu teléfono.",
            "Encender linterna", "Restablecer edición plebeya",
            "Sólo borra el Premium simulado de este dispositivo.", "Apagado Premium en curso",
            "Linterna encendida al máximo", "La linterna ya está apagada",
            "Fuegos artificiales, brillo ceremonial y oscuridad garantizada.",
            "Elegí con qué nivel de elegancia querés apagarla.",
            "Podés completar Premium o volver sin pagar.", "Apagar linterna como un plebeyo",
            "Volver", "APAGADO PREMIUM", "Ya es tuyo", "Oscuridad cinco estrellas",
            "Fuegos artificiales Premium", "Prueba local", "Precio en Google Play",
            "Compra única · Sin suscripción",
            "Esta es una compra simulada: no se cobrará dinero ni se pedirá una tarjeta.",
            "Al continuar, Google Play abrirá el pago oficial para que revises y confirmes la compra.",
            "Simular compra Premium", "Continuar con Google Play", "Ahora no",
            "Icono de linterna", "PUBLICIDAD DE PRUEBA",
            "Necesitamos permiso de cámara solo para controlar el flash.",
            "Apagado normal completado. Dignidad intacta.",
            "Apagado Premium: oscuridad cinco estrellas.",
            "Premium de prueba activado. No se realizó ningún cobro.",
            "Premium de prueba eliminado. Volviste a la edición plebeya.",
            "Premium activado. Gracias por financiar la oscuridad.",
            "Este teléfono no tiene un flash disponible.",
            "No pudimos acceder al flash. Revisá el permiso de cámara.",
            "La cámara está ocupada. Cerrala e intentá otra vez.",
            "El flash no está disponible en este momento.",
            "Google Play no está listo para cobrar en este momento.",
            "El producto Premium todavía no está disponible en Google Play.",
            "Google Play no devolvió una oferta válida para esta compra.",
            "No pudimos abrir el pago de Google Play.",
            "Compra cancelada. La linterna ya está apagada.",
            "La compra no se completó. Podés intentar nuevamente.",
            "El pago está pendiente. Premium se activa al acreditarse.",
            "El pago llegó, pero falta confirmarlo. Abrí la app nuevamente.",
            "Google Play Billing no está configurado en esta compilación.",
        ),
        AppLanguage.ENGLISH to catalog(
            "Languages", "App language", "PREMIUM ACTIVE", "PLEBEIAN EDITION",
            "Ready to light up", "We'll use the highest intensity your phone supports.",
            "Turn on flashlight", "Restore plebeian edition",
            "Only removes simulated Premium from this device.", "Premium shutdown in progress",
            "Flashlight on at maximum", "The flashlight is already off",
            "Fireworks, ceremonial glow, and guaranteed darkness.",
            "Choose how elegantly you want to turn it off.",
            "You can complete Premium or go back without paying.",
            "Turn off flashlight like a plebeian", "Back", "PREMIUM SHUTDOWN",
            "Already yours", "Five-star darkness", "Premium fireworks", "Local test",
            "Price on Google Play", "One-time purchase · No subscription",
            "This is a simulated purchase: no money will be charged and no card will be requested.",
            "When you continue, Google Play will open the official payment so you can review and confirm it.",
            "Simulate Premium purchase", "Continue with Google Play", "Not now",
            "Flashlight icon", "TEST AD",
            "We need camera permission only to control the flash.",
            "Normal shutdown complete. Dignity intact.",
            "Premium shutdown: five-star darkness.",
            "Test Premium activated. No charge was made.",
            "Test Premium removed. You're back to the plebeian edition.",
            "Premium activated. Thanks for funding the darkness.",
            "This phone has no available flash.",
            "We couldn't access the flash. Check the camera permission.",
            "The camera is busy. Close it and try again.",
            "The flash is not available right now.",
            "Google Play is not ready to process payments right now.",
            "The Premium product is not available on Google Play yet.",
            "Google Play did not return a valid offer for this purchase.",
            "We couldn't open Google Play payment.",
            "Purchase cancelled. The flashlight is already off.",
            "The purchase was not completed. You can try again.",
            "Payment is pending. Premium activates when it clears.",
            "The payment arrived, but confirmation is still pending. Open the app again.",
            "Google Play Billing is not configured in this build.",
        ),
        AppLanguage.PORTUGUESE to catalog(
            "Idiomas", "Idioma do aplicativo", "PREMIUM ATIVO", "EDIÇÃO PLEBEIA",
            "Pronta para iluminar", "Usaremos a maior intensidade permitida pelo seu celular.",
            "Acender lanterna", "Restaurar edição plebeia",
            "Remove apenas o Premium simulado deste dispositivo.", "Desligamento Premium em andamento",
            "Lanterna acesa no máximo", "A lanterna já está apagada",
            "Fogos de artifício, brilho cerimonial e escuridão garantida.",
            "Escolha com que nível de elegância você quer apagá-la.",
            "Você pode concluir o Premium ou voltar sem pagar.",
            "Apagar a lanterna como um plebeu", "Voltar", "DESLIGAMENTO PREMIUM",
            "Já é seu", "Escuridão cinco estrelas", "Fogos de artifício Premium", "Teste local",
            "Preço no Google Play", "Compra única · Sem assinatura",
            "Esta é uma compra simulada: nenhum valor será cobrado e nenhum cartão será solicitado.",
            "Ao continuar, o Google Play abrirá o pagamento oficial para você revisar e confirmar a compra.",
            "Simular compra Premium", "Continuar com Google Play", "Agora não",
            "Ícone de lanterna", "ANÚNCIO DE TESTE",
            "Precisamos da permissão da câmera apenas para controlar o flash.",
            "Desligamento normal concluído. Dignidade intacta.",
            "Desligamento Premium: escuridão cinco estrelas.",
            "Premium de teste ativado. Nenhuma cobrança foi realizada.",
            "Premium de teste removido. Você voltou à edição plebeia.",
            "Premium ativado. Obrigado por financiar a escuridão.",
            "Este celular não tem um flash disponível.",
            "Não foi possível acessar o flash. Verifique a permissão da câmera.",
            "A câmera está ocupada. Feche-a e tente novamente.",
            "O flash não está disponível neste momento.",
            "O Google Play não está pronto para cobrar neste momento.",
            "O produto Premium ainda não está disponível no Google Play.",
            "O Google Play não retornou uma oferta válida para esta compra.",
            "Não foi possível abrir o pagamento do Google Play.",
            "Compra cancelada. A lanterna já está apagada.",
            "A compra não foi concluída. Você pode tentar novamente.",
            "O pagamento está pendente. O Premium será ativado após a confirmação.",
            "O pagamento chegou, mas falta confirmá-lo. Abra o aplicativo novamente.",
            "O Google Play Billing não está configurado nesta compilação.",
        ),
        AppLanguage.FRENCH to catalog(
            "Langues", "Langue de l’application", "PREMIUM ACTIF", "ÉDITION PLÉBÉIENNE",
            "Prête à éclairer", "Nous utiliserons l’intensité maximale permise par votre téléphone.",
            "Allumer la lampe", "Rétablir l’édition plébéienne",
            "Supprime uniquement le Premium simulé de cet appareil.", "Extinction Premium en cours",
            "Lampe allumée au maximum", "La lampe est déjà éteinte",
            "Feux d’artifice, éclat cérémoniel et obscurité garantie.",
            "Choisissez avec quel degré d’élégance vous voulez l’éteindre.",
            "Vous pouvez terminer l’achat Premium ou revenir sans payer.",
            "Éteindre la lampe comme un plébéien", "Retour", "EXTINCTION PREMIUM",
            "Déjà à vous", "Obscurité cinq étoiles", "Feux d’artifice Premium", "Test local",
            "Prix sur Google Play", "Achat unique · Sans abonnement",
            "Ceci est un achat simulé : aucun montant ne sera débité et aucune carte ne sera demandée.",
            "En continuant, Google Play ouvrira le paiement officiel pour vérifier et confirmer l’achat.",
            "Simuler l’achat Premium", "Continuer avec Google Play", "Pas maintenant",
            "Icône de lampe", "PUBLICITÉ DE TEST",
            "L’autorisation de la caméra sert uniquement à contrôler le flash.",
            "Extinction normale terminée. Dignité intacte.",
            "Extinction Premium : obscurité cinq étoiles.",
            "Premium de test activé. Aucun paiement n’a été effectué.",
            "Premium de test supprimé. Retour à l’édition plébéienne.",
            "Premium activé. Merci de financer l’obscurité.",
            "Ce téléphone ne dispose d’aucun flash.",
            "Impossible d’accéder au flash. Vérifiez l’autorisation de la caméra.",
            "La caméra est occupée. Fermez-la et réessayez.",
            "Le flash n’est pas disponible pour le moment.",
            "Google Play ne peut pas traiter le paiement pour le moment.",
            "Le produit Premium n’est pas encore disponible sur Google Play.",
            "Google Play n’a renvoyé aucune offre valide pour cet achat.",
            "Impossible d’ouvrir le paiement Google Play.",
            "Achat annulé. La lampe est déjà éteinte.",
            "L’achat n’a pas abouti. Vous pouvez réessayer.",
            "Le paiement est en attente. Premium sera activé après validation.",
            "Le paiement est arrivé, mais doit encore être confirmé. Rouvrez l’application.",
            "Google Play Billing n’est pas configuré dans cette version.",
        ),
        AppLanguage.ITALIAN to catalog(
            "Lingue", "Lingua dell’app", "PREMIUM ATTIVO", "EDIZIONE PLEBEA",
            "Pronta a illuminare", "Useremo la massima intensità consentita dal telefono.",
            "Accendi torcia", "Ripristina edizione plebea",
            "Rimuove solo il Premium simulato da questo dispositivo.", "Spegnimento Premium in corso",
            "Torcia accesa al massimo", "La torcia è già spenta",
            "Fuochi d’artificio, bagliore cerimoniale e oscurità garantita.",
            "Scegli con quanta eleganza vuoi spegnerla.",
            "Puoi completare Premium o tornare indietro senza pagare.",
            "Spegni la torcia come un plebeo", "Indietro", "SPEGNIMENTO PREMIUM",
            "È già tuo", "Oscurità a cinque stelle", "Fuochi d’artificio Premium", "Test locale",
            "Prezzo su Google Play", "Acquisto unico · Nessun abbonamento",
            "Questo è un acquisto simulato: non verrà addebitato denaro né richiesta una carta.",
            "Continuando, Google Play aprirà il pagamento ufficiale per controllare e confermare l’acquisto.",
            "Simula acquisto Premium", "Continua con Google Play", "Non ora",
            "Icona della torcia", "ANNUNCIO DI TEST",
            "L’autorizzazione della fotocamera serve solo a controllare il flash.",
            "Spegnimento normale completato. Dignità intatta.",
            "Spegnimento Premium: oscurità a cinque stelle.",
            "Premium di prova attivato. Non è stato effettuato alcun addebito.",
            "Premium di prova rimosso. Sei tornato all’edizione plebea.",
            "Premium attivato. Grazie per finanziare l’oscurità.",
            "Questo telefono non dispone di un flash.",
            "Impossibile accedere al flash. Controlla l’autorizzazione della fotocamera.",
            "La fotocamera è occupata. Chiudila e riprova.",
            "Il flash non è disponibile in questo momento.",
            "Google Play non può elaborare il pagamento in questo momento.",
            "Il prodotto Premium non è ancora disponibile su Google Play.",
            "Google Play non ha restituito un’offerta valida per questo acquisto.",
            "Impossibile aprire il pagamento Google Play.",
            "Acquisto annullato. La torcia è già spenta.",
            "L’acquisto non è stato completato. Puoi riprovare.",
            "Il pagamento è in sospeso. Premium si attiverà alla conferma.",
            "Il pagamento è arrivato, ma manca la conferma. Riapri l’app.",
            "Google Play Billing non è configurato in questa build.",
        ),
        AppLanguage.GERMAN to catalog(
            "Sprachen", "App-Sprache", "PREMIUM AKTIV", "PLEBEJER-EDITION",
            "Bereit zum Leuchten", "Wir nutzen die höchste Intensität, die dein Handy unterstützt.",
            "Taschenlampe einschalten", "Plebejer-Edition wiederherstellen",
            "Entfernt nur das simulierte Premium von diesem Gerät.", "Premium-Ausschalten läuft",
            "Taschenlampe auf höchster Stufe", "Die Taschenlampe ist bereits aus",
            "Feuerwerk, zeremonieller Glanz und garantierte Dunkelheit.",
            "Wähle, wie elegant du sie ausschalten möchtest.",
            "Du kannst Premium abschließen oder ohne Zahlung zurückgehen.",
            "Taschenlampe wie ein Plebejer ausschalten", "Zurück", "PREMIUM-AUSSCHALTEN",
            "Gehört dir schon", "Fünf-Sterne-Dunkelheit", "Premium-Feuerwerk", "Lokaler Test",
            "Preis bei Google Play", "Einmalkauf · Kein Abonnement",
            "Dies ist ein simulierter Kauf: Es wird nichts berechnet und keine Karte verlangt.",
            "Beim Fortfahren öffnet Google Play die offizielle Zahlung zur Prüfung und Bestätigung.",
            "Premium-Kauf simulieren", "Weiter mit Google Play", "Jetzt nicht",
            "Taschenlampensymbol", "TESTANZEIGE",
            "Die Kameraberechtigung wird nur zur Steuerung des Blitzes benötigt.",
            "Normales Ausschalten abgeschlossen. Würde unversehrt.",
            "Premium-Ausschalten: Fünf-Sterne-Dunkelheit.",
            "Test-Premium aktiviert. Es wurde nichts berechnet.",
            "Test-Premium entfernt. Du bist wieder in der Plebejer-Edition.",
            "Premium aktiviert. Danke für die Finanzierung der Dunkelheit.",
            "Dieses Handy hat keinen verfügbaren Blitz.",
            "Kein Zugriff auf den Blitz. Prüfe die Kameraberechtigung.",
            "Die Kamera ist belegt. Schließe sie und versuche es erneut.",
            "Der Blitz ist derzeit nicht verfügbar.",
            "Google Play kann derzeit keine Zahlung verarbeiten.",
            "Das Premium-Produkt ist bei Google Play noch nicht verfügbar.",
            "Google Play hat kein gültiges Angebot für diesen Kauf geliefert.",
            "Die Google-Play-Zahlung konnte nicht geöffnet werden.",
            "Kauf abgebrochen. Die Taschenlampe ist bereits aus.",
            "Der Kauf wurde nicht abgeschlossen. Du kannst es erneut versuchen.",
            "Die Zahlung steht aus. Premium wird nach Bestätigung aktiviert.",
            "Die Zahlung ist eingegangen, muss aber noch bestätigt werden. Öffne die App erneut.",
            "Google Play Billing ist in diesem Build nicht konfiguriert.",
        ),
        AppLanguage.RUSSIAN to catalog(
            "Языки", "Язык приложения", "PREMIUM АКТИВЕН", "ПЛЕБЕЙСКАЯ ВЕРСИЯ",
            "Готово к освещению", "Будет использована максимальная яркость, доступная на телефоне.",
            "Включить фонарик", "Вернуть плебейскую версию",
            "Удаляет только тестовый Premium с этого устройства.", "Premium-выключение выполняется",
            "Фонарик включён на максимум", "Фонарик уже выключен",
            "Фейерверки, церемониальное сияние и гарантированная темнота.",
            "Выберите, насколько элегантно его выключить.",
            "Можно завершить Premium или вернуться без оплаты.",
            "Выключить фонарик как плебей", "Назад", "PREMIUM-ВЫКЛЮЧЕНИЕ",
            "Уже ваше", "Пятизвёздочная темнота", "Premium-фейерверки", "Локальный тест",
            "Цена в Google Play", "Разовая покупка · Без подписки",
            "Это тестовая покупка: деньги не списываются и карта не запрашивается.",
            "После продолжения Google Play откроет официальный платёж для проверки и подтверждения.",
            "Имитировать покупку Premium", "Продолжить в Google Play", "Не сейчас",
            "Значок фонарика", "ТЕСТОВАЯ РЕКЛАМА",
            "Разрешение камеры нужно только для управления вспышкой.",
            "Обычное выключение завершено. Достоинство сохранено.",
            "Premium-выключение: пятизвёздочная темнота.",
            "Тестовый Premium активирован. Списаний не было.",
            "Тестовый Premium удалён. Вы снова в плебейской версии.",
            "Premium активирован. Спасибо за финансирование темноты.",
            "На этом телефоне нет доступной вспышки.",
            "Не удалось получить доступ к вспышке. Проверьте разрешение камеры.",
            "Камера занята. Закройте её и повторите попытку.",
            "Вспышка сейчас недоступна.",
            "Google Play сейчас не готов обработать платёж.",
            "Продукт Premium пока недоступен в Google Play.",
            "Google Play не вернул подходящее предложение для этой покупки.",
            "Не удалось открыть оплату Google Play.",
            "Покупка отменена. Фонарик уже выключен.",
            "Покупка не завершена. Можно повторить попытку.",
            "Платёж ожидает обработки. Premium активируется после подтверждения.",
            "Платёж поступил, но ещё не подтверждён. Откройте приложение снова.",
            "Google Play Billing не настроен в этой сборке.",
        ),
        AppLanguage.JAPANESE to catalog(
            "言語", "アプリの言語", "PREMIUM 有効", "庶民版",
            "点灯準備完了", "この端末で使える最大の明るさを使用します。",
            "ライトをつける", "庶民版に戻す",
            "この端末のテスト用 Premium だけを削除します。", "Premium 消灯を実行中",
            "ライトは最大の明るさです", "ライトはすでに消えています",
            "花火、儀式の輝き、そして確実な暗闇。",
            "どれくらい優雅に消すか選んでください。",
            "Premium を完了するか、支払わずに戻れます。",
            "庶民らしくライトを消す", "戻る", "PREMIUM 消灯",
            "購入済み", "五つ星の暗闇", "Premium 花火", "ローカルテスト",
            "Google Play での価格", "一回限りの購入 · サブスクリプションなし",
            "これは模擬購入です。料金は発生せず、カード情報も求められません。",
            "続行すると Google Play の公式決済が開き、購入内容を確認できます。",
            "Premium 購入をシミュレート", "Google Play で続行", "今はしない",
            "懐中電灯アイコン", "テスト広告",
            "カメラ権限はフラッシュの制御にのみ使用します。",
            "通常消灯が完了しました。尊厳は無傷です。",
            "Premium 消灯：五つ星の暗闇。",
            "テスト用 Premium を有効にしました。課金は発生していません。",
            "テスト用 Premium を削除しました。庶民版に戻りました。",
            "Premium が有効になりました。暗闇へのご支援に感謝します。",
            "この端末には使用できるフラッシュがありません。",
            "フラッシュにアクセスできません。カメラ権限を確認してください。",
            "カメラが使用中です。閉じてからもう一度お試しください。",
            "現在フラッシュを使用できません。",
            "現在 Google Play で支払いを処理できません。",
            "Premium 商品はまだ Google Play で利用できません。",
            "この購入に有効なオファーが Google Play から返されませんでした。",
            "Google Play の支払いを開けませんでした。",
            "購入をキャンセルしました。ライトはすでに消えています。",
            "購入は完了しませんでした。もう一度お試しください。",
            "支払いは保留中です。確認後に Premium が有効になります。",
            "支払いは届きましたが確認が必要です。アプリをもう一度開いてください。",
            "このビルドでは Google Play Billing が設定されていません。",
        ),
        AppLanguage.CHINESE to catalog(
            "语言", "应用语言", "PREMIUM 已启用", "平民版",
            "准备照明", "将使用此手机支持的最高亮度。",
            "打开手电筒", "恢复平民版",
            "仅移除此设备上的模拟 Premium。", "正在进行 Premium 关灯",
            "手电筒已开到最亮", "手电筒已经关闭",
            "烟花、仪式光效，以及保证到来的黑暗。",
            "选择要以多优雅的方式将它关闭。",
            "你可以完成 Premium，也可以不付款直接返回。",
            "像平民一样关闭手电筒", "返回", "PREMIUM 关灯",
            "已经属于你", "五星级黑暗", "Premium 烟花", "本地测试",
            "Google Play 中的价格", "一次性购买 · 无订阅",
            "这是模拟购买：不会扣款，也不会要求提供银行卡。",
            "继续后，Google Play 将打开官方付款页面供你检查并确认购买。",
            "模拟购买 Premium", "使用 Google Play 继续", "暂时不要",
            "手电筒图标", "测试广告",
            "相机权限仅用于控制闪光灯。",
            "普通关灯已完成。尊严完好无损。",
            "Premium 关灯：五星级黑暗。",
            "测试 Premium 已启用。没有产生任何扣款。",
            "测试 Premium 已移除。你已回到平民版。",
            "Premium 已启用。感谢你资助黑暗。",
            "此手机没有可用的闪光灯。",
            "无法访问闪光灯。请检查相机权限。",
            "相机正被占用。关闭相机后重试。",
            "闪光灯当前不可用。",
            "Google Play 当前无法处理付款。",
            "Premium 商品尚未在 Google Play 上架。",
            "Google Play 没有返回适用于此次购买的有效优惠。",
            "无法打开 Google Play 付款。",
            "购买已取消。手电筒已经关闭。",
            "购买未完成。你可以重试。",
            "付款正在等待处理。确认后将启用 Premium。",
            "付款已收到，但仍需确认。请重新打开应用。",
            "此版本未配置 Google Play Billing。",
        ),
    )

    private fun catalog(vararg values: String): Map<TextKey, String> {
        require(values.size == TextKey.entries.size) {
            "Expected ${TextKey.entries.size} translations, received ${values.size}."
        }
        return TextKey.entries.zip(values).toMap()
    }
}

class PreferencesLanguageStore(context: Context) {
    private val preferences = context.getSharedPreferences(PREFERENCES_NAME, Context.MODE_PRIVATE)

    fun current(): AppLanguage = AppLanguage.fromCode(
        preferences.getString(KEY_LANGUAGE, null) ?: Locale.getDefault().language,
    )

    fun save(language: AppLanguage) {
        preferences.edit { putString(KEY_LANGUAGE, language.code) }
    }

    private companion object {
        const val PREFERENCES_NAME = "app_language"
        const val KEY_LANGUAGE = "selected_language"
    }
}
