package com.linternapremium.app.localization

import android.content.Context
import androidx.core.content.edit
import java.util.Locale

enum class AppLanguage(val code: String, val nativeLabel: String) {
    SPANISH_ARGENTINA("es-AR", "Español (Argentina)"),
    SPANISH_SPAIN("es-ES", "Español (España)"),
    ENGLISH("en", "English"),
    RUSSIAN("ru", "Русский"),
    LATIN("la", "Latine"),
    JAPANESE("ja", "日本語"),
    ITALIAN("it", "Italiano"),
    FRENCH("fr", "Français"),
    GERMAN("de", "Deutsch"),
    DUTCH("nl", "Nederlands"),
    CHINESE_SIMPLIFIED("zh-Hans", "中文（简体）"),
    CHINESE_TRADITIONAL("zh-Hant", "中文（繁體）"),
    PORTUGUESE_BRAZIL("pt-BR", "Português (Brasil)"),
    PORTUGUESE_PORTUGAL("pt-PT", "Português (Portugal)"),
    CATALAN("ca", "Català"),
    BASQUE("eu", "Euskara"),
    GUARANI("gn", "Avañe'ẽ"),
    QUECHUA("quz", "Runa Simi"),
    MANDARIN("cmn-Hans", "普通话"),
    CANTONESE("yue-Hant", "粵語"),
    KOREAN("ko", "한국어");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            val normalized = code
                ?.replace('_', '-')
                ?.lowercase(Locale.ROOT)
                .orEmpty()
            entries.firstOrNull { it.code.lowercase(Locale.ROOT) == normalized }?.let { return it }
            return when {
                normalized == "es-es" -> SPANISH_SPAIN
                normalized.startsWith("es") -> SPANISH_ARGENTINA
                normalized == "pt-pt" -> PORTUGUESE_PORTUGAL
                normalized.startsWith("pt") -> PORTUGUESE_BRAZIL
                normalized.startsWith("yue") -> CANTONESE
                normalized.startsWith("cmn") -> MANDARIN
                normalized.startsWith("zh-hant") || normalized.startsWith("zh-tw") ||
                    normalized.startsWith("zh-hk") || normalized.startsWith("zh-mo") ->
                    CHINESE_TRADITIONAL
                normalized.startsWith("zh") -> CHINESE_SIMPLIFIED
                normalized == "qu" || normalized.startsWith("qu-") -> QUECHUA
                else -> entries.firstOrNull {
                    it.code.substringBefore('-').lowercase(Locale.ROOT) == normalized.substringBefore('-')
                } ?: SPANISH_ARGENTINA
            }
        }
    }
}

enum class TextKey {
    LANGUAGES,
    APP_LANGUAGE,
    PREMIUM_ACTIVE,
    PLEBEIAN_EDITION,
    READY_TO_LIGHT,
    MAX_INTENSITY_HELP,
    TURN_ON,
    RESET_PLEBEIAN,
    RESET_HELP,
    PREMIUM_OFF_PROGRESS,
    TORCH_ON_MAX,
    TORCH_ALREADY_OFF,
    CELEBRATION_HELP,
    CHOOSE_ELEGANCE,
    COMPLETE_OR_RETURN,
    NORMAL_PLEBEIAN_OFF,
    BACK,
    PREMIUM_OFF,
    ALREADY_YOURS,
    FIVE_STAR_DARKNESS,
    FIREWORKS_A11Y,
    LOCAL_TEST,
    PRICE_GOOGLE_PLAY,
    ONE_TIME_NO_SUBSCRIPTION,
    DEMO_PURCHASE_HELP,
    PLAY_PURCHASE_HELP,
    SIMULATE_PURCHASE,
    CONTINUE_PLAY,
    NOT_NOW,
    FLASHLIGHT_ICON,
    TEST_AD,
    CAMERA_PERMISSION,
    NORMAL_OFF_NOTICE,
    PREMIUM_OFF_NOTICE,
    DEMO_PREMIUM_ACTIVATED,
    DEMO_PREMIUM_RESET,
    PREMIUM_ACTIVATED,
    TORCH_NO_FLASH,
    TORCH_ACCESS_ERROR,
    TORCH_BUSY,
    TORCH_UNAVAILABLE,
    BILLING_NOT_READY,
    PRODUCT_UNAVAILABLE,
    INVALID_OFFER,
    OPEN_PAYMENT_ERROR,
    PURCHASE_CANCELLED,
    PURCHASE_FAILED,
    PAYMENT_PENDING,
    PAYMENT_ACK_FAILED,
    BILLING_NOT_CONFIGURED,
}

class LinternaText internal constructor(
    val language: AppLanguage,
    private val values: Map<TextKey, String>,
) {
    operator fun get(key: TextKey): String = values.getValue(key)
}

object LinternaTextCatalog {
    val supportedLanguages: List<AppLanguage> = AppLanguage.entries

    fun forLanguage(language: AppLanguage): LinternaText =
        LinternaText(language, catalogs.getValue(language))

    fun missingKeys(language: AppLanguage): Set<TextKey> =
        TextKey.entries.toSet() - catalogs.getValue(language).keys

    private val catalogs: Map<AppLanguage, Map<TextKey, String>> = mapOf(
        AppLanguage.SPANISH_ARGENTINA to catalog(
            "Idiomas", "Idioma de la aplicación", "PREMIUM ACTIVO", "EDICIÓN PLEBEYA",
            "Lista para iluminar", "Usaremos la mayor intensidad que permita tu teléfono.",
            "Encender linterna", "Restablecer edición plebeya",
            "Sólo borra el Premium simulado de este dispositivo.", "Apagado Premium en curso",
            "Linterna encendida al máximo", "La linterna ya está apagada",
            "Fuegos artificiales, brillo ceremonial y oscuridad garantizada.",
            "Elegí con qué nivel de elegancia querés apagarla.",
            "Podés completar Premium o volver sin pagar.", "Apagar linterna como un plebeyo",
            "Volver", "APAGADO PREMIUM", "Ya es tuyo", "Oscuridad cinco estrellas",
            "Fuegos artificiales Premium", "Prueba local", "Precio en Google Play",
            "Compra única · Sin suscripción",
            "Esta es una compra simulada: no se cobrará dinero ni se pedirá una tarjeta.",
            "Al continuar, Google Play abrirá el pago oficial para que revises y confirmes la compra.",
            "Simular compra Premium", "Continuar con Google Play", "Ahora no",
            "Icono de linterna", "PUBLICIDAD DE PRUEBA",
            "Necesitamos permiso de cámara solo para controlar el flash.",
            "Apagado normal completado. Dignidad intacta.",
            "Apagado Premium: oscuridad cinco estrellas.",
            "Premium de prueba activado. No se realizó ningún cobro.",
            "Premium de prueba eliminado. Volviste a la edición plebeya.",
            "Premium activado. Gracias por financiar la oscuridad.",
            "Este teléfono no tiene un flash disponible.",
            "No pudimos acceder al flash. Revisá el permiso de cámara.",
            "La cámara está ocupada. Cerrala e intentá otra vez.",
            "El flash no está disponible en este momento.",
            "Google Play no está listo para cobrar en este momento.",
            "El producto Premium todavía no está disponible en Google Play.",
            "Google Play no devolvió una oferta válida para esta compra.",
            "No pudimos abrir el pago de Google Play.",
            "Compra cancelada. La linterna ya está apagada.",
            "La compra no se completó. Podés intentar nuevamente.",
            "El pago está pendiente. Premium se activa al acreditarse.",
            "El pago llegó, pero falta confirmarlo. Abrí la app nuevamente.",
            "Google Play Billing no está configurado en esta compilación.",
        ),
        AppLanguage.ENGLISH to catalog(
            "Languages", "App language", "PREMIUM ACTIVE", "PLEBEIAN EDITION",
            "Ready to light up", "We'll use the highest intensity your phone supports.",
            "Turn on flashlight", "Restore plebeian edition",
            "Only removes simulated Premium from this device.", "Premium shutdown in progress",
            "Flashlight on at maximum", "The flashlight is already off",
            "Fireworks, ceremonial glow, and guaranteed darkness.",
            "Choose how elegantly you want to turn it off.",
            "You can complete Premium or go back without paying.",
            "Turn off flashlight like a plebeian", "Back", "PREMIUM SHUTDOWN",
            "Already yours", "Five-star darkness", "Premium fireworks", "Local test",
            "Price on Google Play", "One-time purchase · No subscription",
            "This is a simulated purchase: no money will be charged and no card will be requested.",
            "When you continue, Google Play will open the official payment so you can review and confirm it.",
            "Simulate Premium purchase", "Continue with Google Play", "Not now",
            "Flashlight icon", "TEST AD",
            "We need camera permission only to control the flash.",
            "Normal shutdown complete. Dignity intact.",
            "Premium shutdown: five-star darkness.",
            "Test Premium activated. No charge was made.",
            "Test Premium removed. You're back to the plebeian edition.",
            "Premium activated. Thanks for funding the darkness.",
            "This phone has no available flash.",
            "We couldn't access the flash. Check the camera permission.",
            "The camera is busy. Close it and try again.",
            "The flash is not available right now.",
            "Google Play is not ready to process payments right now.",
            "The Premium product is not available on Google Play yet.",
            "Google Play did not return a valid offer for this purchase.",
            "We couldn't open Google Play payment.",
            "Purchase cancelled. The flashlight is already off.",
            "The purchase was not completed. You can try again.",
            "Payment is pending. Premium activates when it clears.",
            "The payment arrived, but confirmation is still pending. Open the app again.",
            "Google Play Billing is not configured in this build.",
        ),
        AppLanguage.PORTUGUESE_BRAZIL to catalog(
            "Idiomas", "Idioma do aplicativo", "PREMIUM ATIVO", "EDIÇÃO PLEBEIA",
            "Pronta para iluminar", "Usaremos a maior intensidade permitida pelo seu celular.",
            "Acender lanterna", "Restaurar edição plebeia",
            "Remove apenas o Premium simulado deste dispositivo.", "Desligamento Premium em andamento",
            "Lanterna acesa no máximo", "A lanterna já está apagada",
            "Fogos de artifício, brilho cerimonial e escuridão garantida.",
            "Escolha com que nível de elegância você quer apagá-la.",
            "Você pode concluir o Premium ou voltar sem pagar.",
            "Apagar a lanterna como um plebeu", "Voltar", "DESLIGAMENTO PREMIUM",
            "Já é seu", "Escuridão cinco estrelas", "Fogos de artifício Premium", "Teste local",
            "Preço no Google Play", "Compra única · Sem assinatura",
            "Esta é uma compra simulada: nenhum valor será cobrado e nenhum cartão será solicitado.",
            "Ao continuar, o Google Play abrirá o pagamento oficial para você revisar e confirmar a compra.",
            "Simular compra Premium", "Continuar com Google Play", "Agora não",
            "Ícone de lanterna", "ANÚNCIO DE TESTE",
            "Precisamos da permissão da câmera apenas para controlar o flash.",
            "Desligamento normal concluído. Dignidade intacta.",
            "Desligamento Premium: escuridão cinco estrelas.",
            "Premium de teste ativado. Nenhuma cobrança foi realizada.",
            "Premium de teste removido. Você voltou à edição plebeia.",
            "Premium ativado. Obrigado por financiar a escuridão.",
            "Este celular não tem um flash disponível.",
            "Não foi possível acessar o flash. Verifique a permissão da câmera.",
            "A câmera está ocupada. Feche-a e tente novamente.",
            "O flash não está disponível neste momento.",
            "O Google Play não está pronto para cobrar neste momento.",
            "O produto Premium ainda não está disponível no Google Play.",
            "O Google Play não retornou uma oferta válida para esta compra.",
            "Não foi possível abrir o pagamento do Google Play.",
            "Compra cancelada. A lanterna já está apagada.",
            "A compra não foi concluída. Você pode tentar novamente.",
            "O pagamento está pendente. O Premium será ativado após a confirmação.",
            "O pagamento chegou, mas falta confirmá-lo. Abra o aplicativo novamente.",
            "O Google Play Billing não está configurado nesta compilação.",
        ),
        AppLanguage.FRENCH to catalog(
            "Langues", "Langue de l’application", "PREMIUM ACTIF", "ÉDITION PLÉBÉIENNE",
            "Prête à éclairer", "Nous utiliserons l’intensité maximale permise par votre téléphone.",
            "Allumer la lampe", "Rétablir l’édition plébéienne",
            "Supprime uniquement le Premium simulé de cet appareil.", "Extinction Premium en cours",
            "Lampe allumée au maximum", "La lampe est déjà éteinte",
            "Feux d’artifice, éclat cérémoniel et obscurité garantie.",
            "Choisissez avec quel degré d’élégance vous voulez l’éteindre.",
            "Vous pouvez terminer l’achat Premium ou revenir sans payer.",
            "Éteindre la lampe comme un plébéien", "Retour", "EXTINCTION PREMIUM",
            "Déjà à vous", "Obscurité cinq étoiles", "Feux d’artifice Premium", "Test local",
            "Prix sur Google Play", "Achat unique · Sans abonnement",
            "Ceci est un achat simulé : aucun montant ne sera débité et aucune carte ne sera demandée.",
            "En continuant, Google Play ouvrira le paiement officiel pour vérifier et confirmer l’achat.",
            "Simuler l’achat Premium", "Continuer avec Google Play", "Pas maintenant",
            "Icône de lampe", "PUBLICITÉ DE TEST",
            "L’autorisation de la caméra sert uniquement à contrôler le flash.",
            "Extinction normale terminée. Dignité intacte.",
            "Extinction Premium : obscurité cinq étoiles.",
            "Premium de test activé. Aucun paiement n’a été effectué.",
            "Premium de test supprimé. Retour à l’édition plébéienne.",
            "Premium activé. Merci de financer l’obscurité.",
            "Ce téléphone ne dispose d’aucun flash.",
            "Impossible d’accéder au flash. Vérifiez l’autorisation de la caméra.",
            "La caméra est occupée. Fermez-la et réessayez.",
            "Le flash n’est pas disponible pour le moment.",
            "Google Play ne peut pas traiter le paiement pour le moment.",
            "Le produit Premium n’est pas encore disponible sur Google Play.",
            "Google Play n’a renvoyé aucune offre valide pour cet achat.",
            "Impossible d’ouvrir le paiement Google Play.",
            "Achat annulé. La lampe est déjà éteinte.",
            "L’achat n’a pas abouti. Vous pouvez réessayer.",
            "Le paiement est en attente. Premium sera activé après validation.",
            "Le paiement est arrivé, mais doit encore être confirmé. Rouvrez l’application.",
            "Google Play Billing n’est pas configuré dans cette version.",
        ),
        AppLanguage.ITALIAN to catalog(
            "Lingue", "Lingua dell’app", "PREMIUM ATTIVO", "EDIZIONE PLEBEA",
            "Pronta a illuminare", "Useremo la massima intensità consentita dal telefono.",
            "Accendi torcia", "Ripristina edizione plebea",
            "Rimuove solo il Premium simulato da questo dispositivo.", "Spegnimento Premium in corso",
            "Torcia accesa al massimo", "La torcia è già spenta",
            "Fuochi d’artificio, bagliore cerimoniale e oscurità garantita.",
            "Scegli con quanta eleganza vuoi spegnerla.",
            "Puoi completare Premium o tornare indietro senza pagare.",
            "Spegni la torcia come un plebeo", "Indietro", "SPEGNIMENTO PREMIUM",
            "È già tuo", "Oscurità a cinque stelle", "Fuochi d’artificio Premium", "Test locale",
            "Prezzo su Google Play", "Acquisto unico · Nessun abbonamento",
            "Questo è un acquisto simulato: non verrà addebitato denaro né richiesta una carta.",
            "Continuando, Google Play aprirà il pagamento ufficiale per controllare e confermare l’acquisto.",
            "Simula acquisto Premium", "Continua con Google Play", "Non ora",
            "Icona della torcia", "ANNUNCIO DI TEST",
            "L’autorizzazione della fotocamera serve solo a controllare il flash.",
            "Spegnimento normale completato. Dignità intatta.",
            "Spegnimento Premium: oscurità a cinque stelle.",
            "Premium di prova attivato. Non è stato effettuato alcun addebito.",
            "Premium di prova rimosso. Sei tornato all’edizione plebea.",
            "Premium attivato. Grazie per finanziare l’oscurità.",
            "Questo telefono non dispone di un flash.",
            "Impossibile accedere al flash. Controlla l’autorizzazione della fotocamera.",
            "La fotocamera è occupata. Chiudila e riprova.",
            "Il flash non è disponibile in questo momento.",
            "Google Play non può elaborare il pagamento in questo momento.",
            "Il prodotto Premium non è ancora disponibile su Google Play.",
            "Google Play non ha restituito un’offerta valida per questo acquisto.",
            "Impossibile aprire il pagamento Google Play.",
            "Acquisto annullato. La torcia è già spenta.",
            "L’acquisto non è stato completato. Puoi riprovare.",
            "Il pagamento è in sospeso. Premium si attiverà alla conferma.",
            "Il pagamento è arrivato, ma manca la conferma. Riapri l’app.",
            "Google Play Billing non è configurato in questa build.",
        ),
        AppLanguage.GERMAN to catalog(
            "Sprachen", "App-Sprache", "PREMIUM AKTIV", "PLEBEJER-EDITION",
            "Bereit zum Leuchten", "Wir nutzen die höchste Intensität, die dein Handy unterstützt.",
            "Taschenlampe einschalten", "Plebejer-Edition wiederherstellen",
            "Entfernt nur das simulierte Premium von diesem Gerät.", "Premium-Ausschalten läuft",
            "Taschenlampe auf höchster Stufe", "Die Taschenlampe ist bereits aus",
            "Feuerwerk, zeremonieller Glanz und garantierte Dunkelheit.",
            "Wähle, wie elegant du sie ausschalten möchtest.",
            "Du kannst Premium abschließen oder ohne Zahlung zurückgehen.",
            "Taschenlampe wie ein Plebejer ausschalten", "Zurück", "PREMIUM-AUSSCHALTEN",
            "Gehört dir schon", "Fünf-Sterne-Dunkelheit", "Premium-Feuerwerk", "Lokaler Test",
            "Preis bei Google Play", "Einmalkauf · Kein Abonnement",
            "Dies ist ein simulierter Kauf: Es wird nichts berechnet und keine Karte verlangt.",
            "Beim Fortfahren öffnet Google Play die offizielle Zahlung zur Prüfung und Bestätigung.",
            "Premium-Kauf simulieren", "Weiter mit Google Play", "Jetzt nicht",
            "Taschenlampensymbol", "TESTANZEIGE",
            "Die Kameraberechtigung wird nur zur Steuerung des Blitzes benötigt.",
            "Normales Ausschalten abgeschlossen. Würde unversehrt.",
            "Premium-Ausschalten: Fünf-Sterne-Dunkelheit.",
            "Test-Premium aktiviert. Es wurde nichts berechnet.",
            "Test-Premium entfernt. Du bist wieder in der Plebejer-Edition.",
            "Premium aktiviert. Danke für die Finanzierung der Dunkelheit.",
            "Dieses Handy hat keinen verfügbaren Blitz.",
            "Kein Zugriff auf den Blitz. Prüfe die Kameraberechtigung.",
            "Die Kamera ist belegt. Schließe sie und versuche es erneut.",
            "Der Blitz ist derzeit nicht verfügbar.",
            "Google Play kann derzeit keine Zahlung verarbeiten.",
            "Das Premium-Produkt ist bei Google Play noch nicht verfügbar.",
            "Google Play hat kein gültiges Angebot für diesen Kauf geliefert.",
            "Die Google-Play-Zahlung konnte nicht geöffnet werden.",
            "Kauf abgebrochen. Die Taschenlampe ist bereits aus.",
            "Der Kauf wurde nicht abgeschlossen. Du kannst es erneut versuchen.",
            "Die Zahlung steht aus. Premium wird nach Bestätigung aktiviert.",
            "Die Zahlung ist eingegangen, muss aber noch bestätigt werden. Öffne die App erneut.",
            "Google Play Billing ist in diesem Build nicht konfiguriert.",
        ),
        AppLanguage.RUSSIAN to catalog(
            "Языки", "Язык приложения", "PREMIUM АКТИВЕН", "ПЛЕБЕЙСКАЯ ВЕРСИЯ",
            "Готово к освещению", "Будет использована максимальная яркость, доступная на телефоне.",
            "Включить фонарик", "Вернуть плебейскую версию",
            "Удаляет только тестовый Premium с этого устройства.", "Premium-выключение выполняется",
            "Фонарик включён на максимум", "Фонарик уже выключен",
            "Фейерверки, церемониальное сияние и гарантированная темнота.",
            "Выберите, насколько элегантно его выключить.",
            "Можно завершить Premium или вернуться без оплаты.",
            "Выключить фонарик как плебей", "Назад", "PREMIUM-ВЫКЛЮЧЕНИЕ",
            "Уже ваше", "Пятизвёздочная темнота", "Premium-фейерверки", "Локальный тест",
            "Цена в Google Play", "Разовая покупка · Без подписки",
            "Это тестовая покупка: деньги не списываются и карта не запрашивается.",
            "После продолжения Google Play откроет официальный платёж для проверки и подтверждения.",
            "Имитировать покупку Premium", "Продолжить в Google Play", "Не сейчас",
            "Значок фонарика", "ТЕСТОВАЯ РЕКЛАМА",
            "Разрешение камеры нужно только для управления вспышкой.",
            "Обычное выключение завершено. Достоинство сохранено.",
            "Premium-выключение: пятизвёздочная темнота.",
            "Тестовый Premium активирован. Списаний не было.",
            "Тестовый Premium удалён. Вы снова в плебейской версии.",
            "Premium активирован. Спасибо за финансирование темноты.",
            "На этом телефоне нет доступной вспышки.",
            "Не удалось получить доступ к вспышке. Проверьте разрешение камеры.",
            "Камера занята. Закройте её и повторите попытку.",
            "Вспышка сейчас недоступна.",
            "Google Play сейчас не готов обработать платёж.",
            "Продукт Premium пока недоступен в Google Play.",
            "Google Play не вернул подходящее предложение для этой покупки.",
            "Не удалось открыть оплату Google Play.",
            "Покупка отменена. Фонарик уже выключен.",
            "Покупка не завершена. Можно повторить попытку.",
            "Платёж ожидает обработки. Premium активируется после подтверждения.",
            "Платёж поступил, но ещё не подтверждён. Откройте приложение снова.",
            "Google Play Billing не настроен в этой сборке.",
        ),
        AppLanguage.JAPANESE to catalog(
            "言語", "アプリの言語", "PREMIUM 有効", "庶民版",
            "点灯準備完了", "この端末で使える最大の明るさを使用します。",
            "ライトをつける", "庶民版に戻す",
            "この端末のテスト用 Premium だけを削除します。", "Premium 消灯を実行中",
            "ライトは最大の明るさです", "ライトはすでに消えています",
            "花火、儀式の輝き、そして確実な暗闇。",
            "どれくらい優雅に消すか選んでください。",
            "Premium を完了するか、支払わずに戻れます。",
            "庶民らしくライトを消す", "戻る", "PREMIUM 消灯",
            "購入済み", "五つ星の暗闇", "Premium 花火", "ローカルテスト",
            "Google Play での価格", "一回限りの購入 · サブスクリプションなし",
            "これは模擬購入です。料金は発生せず、カード情報も求められません。",
            "続行すると Google Play の公式決済が開き、購入内容を確認できます。",
            "Premium 購入をシミュレート", "Google Play で続行", "今はしない",
            "懐中電灯アイコン", "テスト広告",
            "カメラ権限はフラッシュの制御にのみ使用します。",
            "通常消灯が完了しました。尊厳は無傷です。",
            "Premium 消灯：五つ星の暗闇。",
            "テスト用 Premium を有効にしました。課金は発生していません。",
            "テスト用 Premium を削除しました。庶民版に戻りました。",
            "Premium が有効になりました。暗闇へのご支援に感謝します。",
            "この端末には使用できるフラッシュがありません。",
            "フラッシュにアクセスできません。カメラ権限を確認してください。",
            "カメラが使用中です。閉じてからもう一度お試しください。",
            "現在フラッシュを使用できません。",
            "現在 Google Play で支払いを処理できません。",
            "Premium 商品はまだ Google Play で利用できません。",
            "この購入に有効なオファーが Google Play から返されませんでした。",
            "Google Play の支払いを開けませんでした。",
            "購入をキャンセルしました。ライトはすでに消えています。",
            "購入は完了しませんでした。もう一度お試しください。",
            "支払いは保留中です。確認後に Premium が有効になります。",
            "支払いは届きましたが確認が必要です。アプリをもう一度開いてください。",
            "このビルドでは Google Play Billing が設定されていません。",
        ),
        AppLanguage.CHINESE_SIMPLIFIED to catalog(
            "语言", "应用语言", "PREMIUM 已启用", "平民版",
            "准备照明", "将使用此手机支持的最高亮度。",
            "打开手电筒", "恢复平民版",
            "仅移除此设备上的模拟 Premium。", "正在进行 Premium 关灯",
            "手电筒已开到最亮", "手电筒已经关闭",
            "烟花、仪式光效，以及保证到来的黑暗。",
            "选择要以多优雅的方式将它关闭。",
            "你可以完成 Premium，也可以不付款直接返回。",
            "像平民一样关闭手电筒", "返回", "PREMIUM 关灯",
            "已经属于你", "五星级黑暗", "Premium 烟花", "本地测试",
            "Google Play 中的价格", "一次性购买 · 无订阅",
            "这是模拟购买：不会扣款，也不会要求提供银行卡。",
            "继续后，Google Play 将打开官方付款页面供你检查并确认购买。",
            "模拟购买 Premium", "使用 Google Play 继续", "暂时不要",
            "手电筒图标", "测试广告",
            "相机权限仅用于控制闪光灯。",
            "普通关灯已完成。尊严完好无损。",
            "Premium 关灯：五星级黑暗。",
            "测试 Premium 已启用。没有产生任何扣款。",
            "测试 Premium 已移除。你已回到平民版。",
            "Premium 已启用。感谢你资助黑暗。",
            "此手机没有可用的闪光灯。",
            "无法访问闪光灯。请检查相机权限。",
            "相机正被占用。关闭相机后重试。",
            "闪光灯当前不可用。",
            "Google Play 当前无法处理付款。",
            "Premium 商品尚未在 Google Play 上架。",
            "Google Play 没有返回适用于此次购买的有效优惠。",
            "无法打开 Google Play 付款。",
            "购买已取消。手电筒已经关闭。",
            "购买未完成。你可以重试。",
            "付款正在等待处理。确认后将启用 Premium。",
            "付款已收到，但仍需确认。请重新打开应用。",
            "此版本未配置 Google Play Billing。",
        ),
    ).let { base ->
        base + mapOf(
            AppLanguage.SPANISH_SPAIN to (
                base.getValue(AppLanguage.SPANISH_ARGENTINA) + mapOf(
                    TextKey.MAX_INTENSITY_HELP to "Usaremos la mayor intensidad que permita tu teléfono.",
                    TextKey.CHOOSE_ELEGANCE to "Elige con qué nivel de elegancia quieres apagarla.",
                    TextKey.COMPLETE_OR_RETURN to "Puedes completar Premium o volver sin pagar.",
                    TextKey.NORMAL_PLEBEIAN_OFF to "Apagar la linterna como un plebeyo",
                    TextKey.DEMO_PURCHASE_HELP to "Esta es una compra simulada: no se cobrará dinero ni se pedirá una tarjeta.",
                    TextKey.PLAY_PURCHASE_HELP to "Al continuar, Google Play abrirá el pago oficial para que revises y confirmes la compra.",
                    TextKey.TORCH_ACCESS_ERROR to "No hemos podido acceder al flash. Revisa el permiso de cámara.",
                    TextKey.TORCH_BUSY to "La cámara está ocupada. Ciérrala e inténtalo de nuevo.",
                    TextKey.PURCHASE_FAILED to "La compra no se ha completado. Puedes intentarlo de nuevo.",
                    TextKey.PAYMENT_ACK_FAILED to "El pago ha llegado, pero falta confirmarlo. Abre la aplicación de nuevo.",
                )
            ),
            AppLanguage.LATIN to catalog(
                "Linguae", "Lingua applicationis", "PREMIUM ACTIVUM", "EDITIO PLEBEIA",
                "Parata ad illuminandum", "Maxima luce quam telephonum tuum sustinet utemur.",
                "Lucernam accende", "Editionem plebeiam restitue",
                "Premium simulatum tantum ex hoc instrumento delet.", "Exstinctio Premium agitur",
                "Lucerna maxima luce accensa", "Lucerna iam exstincta est",
                "Ignes festi, fulgor caerimonialis et tenebrae certae.",
                "Elige quam eleganter eam exstinguere velis.",
                "Premium perficere aut sine pretio redire potes.",
                "Lucernam velut plebeius exstingue", "Redi", "EXSTINCTIO PREMIUM",
                "Iam tuum est", "Tenebrae quinque stellarum", "Ignes festi Premium", "Probatio localis",
                "Pretium in Google Play", "Emptio unica · Nulla subscriptio",
                "Haec emptio simulata est: nulla pecunia exigetur nec charta petetur.",
                "Pergens Google Play solutionem officialem aperiet ut emptionem recognoscas et confirmes.",
                "Emptionem Premium simula", "Perge cum Google Play", "Non nunc",
                "Imago lucernae", "NUNTIUS EXPERIMENTALIS",
                "Licentia camerae tantum ad fulgorem regendum requiritur.",
                "Exstinctio communis perfecta. Dignitas integra.",
                "Exstinctio Premium: tenebrae quinque stellarum.",
                "Premium probationis activatum. Nihil exactum est.",
                "Premium probationis deletum. Ad editionem plebeiam rediisti.",
                "Premium activatum. Gratias quod tenebras sustines.",
                "Hoc telephonum fulgorem aptum non habet.",
                "Fulgor adiri non potuit. Licentiam camerae inspice.",
                "Camera occupata est. Claude eam et iterum conare.",
                "Fulgor nunc praesto non est.",
                "Google Play nunc solutiones tractare non potest.",
                "Productum Premium nondum in Google Play praesto est.",
                "Google Play oblationem validam huic emptioni non reddidit.",
                "Solutio Google Play aperiri non potuit.",
                "Emptio revocata. Lucerna iam exstincta est.",
                "Emptio non perfecta est. Iterum conari potes.",
                "Solutio pendet. Premium post confirmationem activatur.",
                "Solutio advenit, sed confirmatio deest. Applicationem iterum aperi.",
                "Google Play Billing in hac versione non configuratur.",
            ),
            AppLanguage.DUTCH to catalog(
                "Talen", "App-taal", "PREMIUM ACTIEF", "PLEBEJERSE EDITIE",
                "Klaar om te schijnen", "We gebruiken de hoogste intensiteit die je telefoon ondersteunt.",
                "Zaklamp inschakelen", "Plebejerse editie herstellen",
                "Verwijdert alleen de gesimuleerde Premium van dit apparaat.", "Premium-uitschakeling bezig",
                "Zaklamp op maximale sterkte", "De zaklamp is al uit",
                "Vuurwerk, ceremoniële gloed en gegarandeerde duisternis.",
                "Kies hoe elegant je hem wilt uitschakelen.",
                "Je kunt Premium afronden of teruggaan zonder te betalen.",
                "Zaklamp uitschakelen als een plebejer", "Terug", "PREMIUM-UITSCHAKELING",
                "Al van jou", "Vijfsterrenduisternis", "Premium-vuurwerk", "Lokale test",
                "Prijs op Google Play", "Eenmalige aankoop · Geen abonnement",
                "Dit is een gesimuleerde aankoop: er wordt niets afgeschreven en er wordt geen kaart gevraagd.",
                "Als je doorgaat, opent Google Play de officiële betaling zodat je de aankoop kunt controleren en bevestigen.",
                "Premium-aankoop simuleren", "Doorgaan met Google Play", "Niet nu",
                "Zaklamppictogram", "TESTADVERTENTIE",
                "Cameratoestemming is alleen nodig om de flitser te bedienen.",
                "Normaal uitschakelen voltooid. Waardigheid intact.",
                "Premium-uitschakeling: vijfsterrenduisternis.",
                "Test-Premium geactiveerd. Er is niets in rekening gebracht.",
                "Test-Premium verwijderd. Je bent terug bij de plebejerse editie.",
                "Premium geactiveerd. Bedankt voor het financieren van de duisternis.",
                "Deze telefoon heeft geen beschikbare flitser.",
                "We konden de flitser niet openen. Controleer de cameratoestemming.",
                "De camera is bezet. Sluit hem en probeer het opnieuw.",
                "De flitser is momenteel niet beschikbaar.",
                "Google Play kan momenteel geen betalingen verwerken.",
                "Het Premium-product is nog niet beschikbaar op Google Play.",
                "Google Play heeft geen geldig aanbod voor deze aankoop teruggegeven.",
                "We konden de Google Play-betaling niet openen.",
                "Aankoop geannuleerd. De zaklamp is al uit.",
                "De aankoop is niet voltooid. Je kunt het opnieuw proberen.",
                "De betaling is in behandeling. Premium wordt na bevestiging geactiveerd.",
                "De betaling is ontvangen, maar moet nog worden bevestigd. Open de app opnieuw.",
                "Google Play Billing is niet ingesteld in deze build.",
            ),
            AppLanguage.CHINESE_TRADITIONAL to catalog(
                "語言", "應用程式語言", "PREMIUM 已啟用", "平民版",
                "準備照明", "將使用此手機支援的最高亮度。",
                "開啟手電筒", "恢復平民版",
                "只會移除此裝置上的模擬 Premium。", "正在進行 Premium 關燈",
                "手電筒已開到最亮", "手電筒已經關閉",
                "煙火、儀式光效，以及保證到來的黑暗。",
                "選擇要以多優雅的方式將它關閉。",
                "你可以完成 Premium，也可以不付款直接返回。",
                "像平民一樣關閉手電筒", "返回", "PREMIUM 關燈",
                "已經屬於你", "五星級黑暗", "Premium 煙火", "本機測試",
                "Google Play 中的價格", "一次性購買 · 無訂閱",
                "這是模擬購買：不會扣款，也不會要求提供信用卡。",
                "繼續後，Google Play 將開啟官方付款頁面，讓你檢查並確認購買。",
                "模擬購買 Premium", "使用 Google Play 繼續", "暫時不要",
                "手電筒圖示", "測試廣告",
                "相機權限只用於控制閃光燈。",
                "一般關燈已完成。尊嚴完好無損。",
                "Premium 關燈：五星級黑暗。",
                "測試 Premium 已啟用。沒有產生任何扣款。",
                "測試 Premium 已移除。你已回到平民版。",
                "Premium 已啟用。感謝你資助黑暗。",
                "此手機沒有可用的閃光燈。",
                "無法存取閃光燈。請檢查相機權限。",
                "相機正被占用。關閉相機後再試一次。",
                "閃光燈目前無法使用。",
                "Google Play 目前無法處理付款。",
                "Premium 商品尚未在 Google Play 上架。",
                "Google Play 沒有傳回適用於此次購買的有效優惠。",
                "無法開啟 Google Play 付款。",
                "購買已取消。手電筒已經關閉。",
                "購買未完成。你可以再試一次。",
                "付款正在等待處理。確認後將啟用 Premium。",
                "付款已收到，但仍需確認。請重新開啟應用程式。",
                "此版本未設定 Google Play Billing。",
            ),
            AppLanguage.PORTUGUESE_PORTUGAL to catalog(
                "Idiomas", "Idioma da aplicação", "PREMIUM ATIVO", "EDIÇÃO PLEBEIA",
                "Pronta para iluminar", "Usaremos a maior intensidade permitida pelo teu telemóvel.",
                "Ligar lanterna", "Restaurar edição plebeia",
                "Remove apenas o Premium simulado deste dispositivo.", "Desativação Premium em curso",
                "Lanterna ligada no máximo", "A lanterna já está desligada",
                "Fogo de artifício, brilho cerimonial e escuridão garantida.",
                "Escolhe com que nível de elegância a queres desligar.",
                "Podes concluir o Premium ou voltar sem pagar.",
                "Desligar a lanterna como um plebeu", "Voltar", "DESATIVAÇÃO PREMIUM",
                "Já é teu", "Escuridão cinco estrelas", "Fogo de artifício Premium", "Teste local",
                "Preço no Google Play", "Compra única · Sem subscrição",
                "Esta é uma compra simulada: não será cobrado dinheiro nem será pedido um cartão.",
                "Ao continuar, o Google Play abrirá o pagamento oficial para reveres e confirmares a compra.",
                "Simular compra Premium", "Continuar com o Google Play", "Agora não",
                "Ícone de lanterna", "ANÚNCIO DE TESTE",
                "Precisamos da permissão da câmara apenas para controlar o flash.",
                "Desativação normal concluída. Dignidade intacta.",
                "Desativação Premium: escuridão cinco estrelas.",
                "Premium de teste ativado. Não foi feita qualquer cobrança.",
                "Premium de teste removido. Voltaste à edição plebeia.",
                "Premium ativado. Obrigado por financiares a escuridão.",
                "Este telemóvel não tem um flash disponível.",
                "Não foi possível aceder ao flash. Verifica a permissão da câmara.",
                "A câmara está ocupada. Fecha-a e tenta novamente.",
                "O flash não está disponível neste momento.",
                "O Google Play não consegue processar pagamentos neste momento.",
                "O produto Premium ainda não está disponível no Google Play.",
                "O Google Play não devolveu uma oferta válida para esta compra.",
                "Não foi possível abrir o pagamento do Google Play.",
                "Compra cancelada. A lanterna já está desligada.",
                "A compra não foi concluída. Podes tentar novamente.",
                "O pagamento está pendente. O Premium será ativado após confirmação.",
                "O pagamento chegou, mas ainda falta confirmá-lo. Abre novamente a aplicação.",
                "O Google Play Billing não está configurado nesta compilação.",
            ),
            AppLanguage.CATALAN to catalog(
                "Idiomes", "Idioma de l’aplicació", "PREMIUM ACTIU", "EDICIÓ PLEBEA",
                "A punt per il·luminar", "Utilitzarem la intensitat màxima que permeti el teu telèfon.",
                "Encendre la llanterna", "Restablir l’edició plebea",
                "Només elimina el Premium simulat d’aquest dispositiu.", "Apagada Premium en curs",
                "Llanterna encesa al màxim", "La llanterna ja està apagada",
                "Focs artificials, resplendor cerimonial i foscor garantida.",
                "Tria amb quin nivell d’elegància la vols apagar.",
                "Pots completar Premium o tornar sense pagar.",
                "Apagar la llanterna com un plebeu", "Tornar", "APAGADA PREMIUM",
                "Ja és teu", "Foscor de cinc estrelles", "Focs artificials Premium", "Prova local",
                "Preu a Google Play", "Compra única · Sense subscripció",
                "Aquesta és una compra simulada: no es cobrarà res ni es demanarà cap targeta.",
                "En continuar, Google Play obrirà el pagament oficial perquè revisis i confirmis la compra.",
                "Simular compra Premium", "Continuar amb Google Play", "Ara no",
                "Icona de llanterna", "ANUNCI DE PROVA",
                "Només necessitem permís de càmera per controlar el flaix.",
                "Apagada normal completada. Dignitat intacta.",
                "Apagada Premium: foscor de cinc estrelles.",
                "Premium de prova activat. No s’ha fet cap cobrament.",
                "Premium de prova eliminat. Has tornat a l’edició plebea.",
                "Premium activat. Gràcies per finançar la foscor.",
                "Aquest telèfon no té cap flaix disponible.",
                "No hem pogut accedir al flaix. Revisa el permís de càmera.",
                "La càmera està ocupada. Tanca-la i torna-ho a provar.",
                "El flaix no està disponible ara mateix.",
                "Google Play no pot processar pagaments ara mateix.",
                "El producte Premium encara no està disponible a Google Play.",
                "Google Play no ha retornat cap oferta vàlida per a aquesta compra.",
                "No hem pogut obrir el pagament de Google Play.",
                "Compra cancel·lada. La llanterna ja està apagada.",
                "La compra no s’ha completat. Pots tornar-ho a provar.",
                "El pagament està pendent. Premium s’activarà quan es confirmi.",
                "El pagament ha arribat, però falta confirmar-lo. Torna a obrir l’aplicació.",
                "Google Play Billing no està configurat en aquesta compilació.",
            ),
            AppLanguage.BASQUE to catalog(
                "Hizkuntzak", "Aplikazioaren hizkuntza", "PREMIUM AKTIBO", "PLEBEIOEN EDIZIOA",
                "Argitzeko prest", "Telefonoak onartzen duen intentsitaterik handiena erabiliko dugu.",
                "Piztu linterna", "Leheneratu plebeioen edizioa",
                "Gailu honetako Premium simulatua bakarrik kentzen du.", "Premium itzaltzea martxan",
                "Linterna gehienezko indarrarekin piztuta", "Linterna dagoeneko itzalita dago",
                "Su artifizialak, zeremonia-distira eta iluntasun bermatua.",
                "Aukeratu zenbat dotoretasunez itzali nahi duzun.",
                "Premium osatu edo ordaindu gabe itzul zaitezke.",
                "Itzali linterna plebeio baten moduan", "Itzuli", "PREMIUM ITZALTZEA",
                "Zurea da dagoeneko", "Bost izarreko iluntasuna", "Premium su artifizialak", "Tokiko proba",
                "Google Play-ko prezioa", "Erosketa bakarra · Harpidetzarik gabe",
                "Erosketa simulatua da: ez da dirurik kobratuko eta ez da txartelik eskatuko.",
                "Jarraitzean, Google Play-k ordainketa ofiziala irekiko du erosketa berrikusi eta baieztatzeko.",
                "Simulatu Premium erosketa", "Jarraitu Google Play-rekin", "Orain ez",
                "Linternaren ikonoa", "PROBAKO IRAGARKIA",
                "Kameraren baimena flasha kontrolatzeko bakarrik behar dugu.",
                "Itzaltze arrunta osatu da. Duintasuna bere horretan.",
                "Premium itzaltzea: bost izarreko iluntasuna.",
                "Probako Premium aktibatu da. Ez da ezer kobratu.",
                "Probako Premium kendu da. Plebeioen ediziora itzuli zara.",
                "Premium aktibatu da. Eskerrik asko iluntasuna finantzatzeagatik.",
                "Telefono honek ez du flash erabilgarririk.",
                "Ezin izan dugu flasha atzitu. Egiaztatu kameraren baimena.",
                "Kamera okupatuta dago. Itxi eta saiatu berriro.",
                "Flasha ez dago erabilgarri une honetan.",
                "Google Play-k ezin ditu ordainketak prozesatu une honetan.",
                "Premium produktua ez dago oraindik erabilgarri Google Play-n.",
                "Google Play-k ez du eskaintza baliozkorik itzuli erosketa honetarako.",
                "Ezin izan dugu Google Play-ren ordainketa ireki.",
                "Erosketa bertan behera utzi da. Linterna dagoeneko itzalita dago.",
                "Erosketa ez da osatu. Berriro saia zaitezke.",
                "Ordainketa zain dago. Premium baieztatutakoan aktibatuko da.",
                "Ordainketa iritsi da, baina baieztatu behar da. Ireki berriro aplikazioa.",
                "Google Play Billing ez dago konfiguratuta build honetan.",
            ),
            AppLanguage.GUARANI to catalog(
                "Ñe'ẽnguéra", "Tembiporu ñe'ẽ", "PREMIUM OIKÓMA", "PLEBEYO REMBIASA",
                "Oĩma ohesape hag̃ua", "Jaiporúta pe tesape mbaretevéva ne pumbyry ohejáva.",
                "Mimbiha myendy", "Plebeyo rembiapo mbojevy",
                "Oipe'a Premium ñembosarái ko pumbyrýgui añónte.", "Premium ñembogue oñemboguata",
                "Mimbiha hendy mbaretevépe", "Mimbiha oguéma voi",
                "Tataindy jegua, tesape arete ha pytũ añeteguáva.",
                "Eiporavo mba'éichapa porã remboguese.",
                "Ikatu remohu'ã Premium térã rejevy repaga'ỹre.",
                "Embogue mimbiha plebeyoicha", "Jevy", "PREMIUM ÑEMBOGUE",
                "Nemba'éma", "Pytũ po mbyja rehegua", "Premium tataindy jegua", "Ñeha'ã ko'ápe",
                "Hepy Google Play-pe", "Peteĩ jeogua · Suscripción'ỹre",
                "Kóva jeogua ñembosarái: ndojekobrái mba'eve ha ndojejeruréi tarjeta.",
                "Rekontinuáramo, Google Play oipe'áta pago oficial ehecha ha emoañete hag̃ua jeogua.",
                "Eha'ã jeogua Premium", "Eho Google Play ndive", "Ani ko'ág̃a",
                "Mimbiha ra'anga", "MARANDU ÑEHA'Ã",
                "Roikotevẽ cámara ñemoneĩ flash roisãmbyhy hag̃ua añónte.",
                "Ñembogue jepivegua oikóma. Tekoporã opyta.",
                "Premium ñembogue: pytũ po mbyja rehegua.",
                "Premium ñeha'ã oikóma. Ndojekobrái mba'eve.",
                "Premium ñeha'ã ojepe'áma. Rejevýma plebeyo rembiapópe.",
                "Premium oikóma. Aguyje eipytyvõ haguére pytũme.",
                "Ko pumbyry ndoguerekói flash ojeporukuaáva.",
                "Ndaikatúi roike flash-pe. Ehecha cámara ñemoneĩ.",
                "Cámara ojeporuhína. Emboty ha eha'ã jey.",
                "Flash ndojeporukuaái ko'ág̃a.",
                "Google Play ndaikatúi omba'apo pago rehe ko'ág̃a.",
                "Premium mba'e ndojeporukuaái gueteri Google Play-pe.",
                "Google Play nome'ẽi oferta oikóva ko jeoguápe.",
                "Ndaikatúi roipe'a Google Play pago.",
                "Jeogua ojeheja. Mimbiha oguéma voi.",
                "Jeogua noñemohu'ãi. Ikatu reha'ã jey.",
                "Pago oha'arõhína. Premium oikóta oñemoañete rire.",
                "Pago og̃uahẽma, hákatu oñemoañete va'erã. Eipe'a jey tembiporu.",
                "Google Play Billing noñemohendái ko compilación-pe.",
            ),
            AppLanguage.QUECHUA to catalog(
                "Rimaykuna", "Aplicacionpa rimaynin", "PREMIUM LLANK'ACHKAN", "LLAQTA RUNAPA ÑIQIN",
                "K'anchachinapaq listo", "Telefonoyki chaskinman hina aswan kallpawan k'anchachisunchik.",
                "Linternata hap'ichiy", "Llaqta runapa ñiqinta kutichiy",
                "Kay dispositivopi yachachinapaq Premium-llata chinkachin.", "Premium wañuchiy purichkan",
                "Linterna aswan kallpawan hap'ichisqa", "Linterna ñam wañusqaña",
                "Nina pukllay, raymi k'anchay, hinallataq chiqap tutayay.",
                "Imayna sumaqta wañuchiyta munanki chayta akllay.",
                "Premiumta tukuchiyta utaq mana qullqita quspa kutiyta atinki.",
                "Linternata llaqta runahina wañuchiy", "Kutiy", "PREMIUM WAÑUCHIY",
                "Ñam qanpataña", "Pichqa ch'askayuq tutayay", "Premium nina pukllay", "Kaypi yachachiy",
                "Google Play nisqapi chanin", "Huk kuti rantiy · Mana suscripciónniyuq",
                "Kayqa yachachinapaq rantiyllam: mana qullqi hurqunqakuchu nitaq tarjeta mañakunqakuchu.",
                "Qatiqtiyki, Google Play oficial pagota kicharinqa rantiyta qhawaspa takyachinaykipaq.",
                "Premium rantiyta yachachiy", "Google Playwan qatiy", "Kunanqa ama",
                "Linterna unancha", "YACHACHINAPAQ WILLAY",
                "Cámarapa saqillayninta flash kamachinapaqllam munayku.",
                "Sapa wañuchiy tukusqa. Yupaychay mana wakllisqa.",
                "Premium wañuchiy: pichqa ch'askayuq tutayay.",
                "Yachachinapaq Premium hap'ichisqa. Mana imapas cobrasqachu.",
                "Yachachinapaq Premium chinkachisqa. Llaqta runapa ñiqinman kutirqanki.",
                "Premium hap'ichisqa. Tutayayta yanapasqaykimanta sulpayki.",
                "Kay telefonopi mana flash kanchu.",
                "Flashman mana yaykuyta atirqaykuchu. Cámarapa saqillayninta qhaway.",
                "Cámara llamk'achkan. Wichq'aspa musuqmanta ruray.",
                "Flash kunanqa mana llamk'anchu.",
                "Google Play kunanqa mana pagota ruwanchu.",
                "Premium productoqa manaraq Google Playpi kanchu.",
                "Google Play mana allin ofertata kay rantiypaq kutichirqachu.",
                "Google Play pagota mana kichayta atirqaykuchu.",
                "Rantiy sayachisqa. Linterna ñam wañusqaña.",
                "Rantiy mana tukusqachu. Musuqmanta rurayta atinki.",
                "Pago suyachkan. Takyachisqa kaptin Premium hap'ichikunqa.",
                "Pago chayamunña, ichaqa takyachina kachkan. Aplicacionta musuqmanta kichay.",
                "Google Play Billing mana kay buildpi wakichisqachu.",
            ),
            AppLanguage.MANDARIN to base.getValue(AppLanguage.CHINESE_SIMPLIFIED),
            AppLanguage.CANTONESE to catalog(
                "語言", "應用程式語言", "PREMIUM 已啟用", "平民版",
                "準備好照明", "會用你部手機支援嘅最高亮度。",
                "開著電筒", "恢復平民版",
                "只會刪除呢部裝置嘅模擬 Premium。", "Premium 熄燈進行中",
                "電筒已經開到最光", "電筒已經熄咗",
                "煙花、儀式光效，同埋保證有嘅黑暗。",
                "揀你想幾優雅咁熄咗佢。",
                "你可以完成 Premium，或者唔使畀錢直接返去。",
                "好似平民咁熄電筒", "返回", "PREMIUM 熄燈",
                "已經係你嘅", "五星級黑暗", "Premium 煙花", "本機測試",
                "Google Play 價格", "一次過購買 · 冇訂閱",
                "呢個係模擬購買：唔會扣錢，亦唔會問你攞信用卡。",
                "繼續之後，Google Play 會開官方付款頁面，畀你檢查同確認購買。",
                "模擬購買 Premium", "用 Google Play 繼續", "而家唔要",
                "電筒圖示", "測試廣告",
                "相機權限只會用嚟控制閃光燈。",
                "普通熄燈完成。尊嚴完整無缺。",
                "Premium 熄燈：五星級黑暗。",
                "測試 Premium 已啟用。冇收過任何費用。",
                "測試 Premium 已刪除。你返咗去平民版。",
                "Premium 已啟用。多謝你資助黑暗。",
                "呢部手機冇可用嘅閃光燈。",
                "存取唔到閃光燈。請檢查相機權限。",
                "相機用緊。閂咗佢再試。",
                "閃光燈而家用唔到。",
                "Google Play 而家處理唔到付款。",
                "Premium 商品仲未喺 Google Play 上架。",
                "Google Play 冇傳回適合呢次購買嘅有效優惠。",
                "開唔到 Google Play 付款。",
                "購買已取消。電筒已經熄咗。",
                "購買未完成。你可以再試。",
                "付款等緊處理。確認之後會啟用 Premium。",
                "付款已收到，但仲要確認。請重新開啟應用程式。",
                "呢個版本未設定 Google Play Billing。",
            ),
            AppLanguage.KOREAN to catalog(
                "언어", "앱 언어", "PREMIUM 활성화", "평민판",
                "조명 준비 완료", "휴대전화가 지원하는 가장 높은 밝기를 사용합니다.",
                "손전등 켜기", "평민판으로 복원",
                "이 기기의 모의 Premium만 삭제합니다.", "Premium 끄기 진행 중",
                "손전등 최대 밝기로 켜짐", "손전등이 이미 꺼져 있습니다",
                "불꽃놀이, 의식의 빛, 그리고 보장된 어둠.",
                "얼마나 우아하게 끌지 선택하세요.",
                "Premium 구매를 완료하거나 결제 없이 돌아갈 수 있습니다.",
                "평민처럼 손전등 끄기", "뒤로", "PREMIUM 끄기",
                "이미 보유 중", "별 다섯 개짜리 어둠", "Premium 불꽃놀이", "로컬 테스트",
                "Google Play 가격", "일회성 구매 · 구독 없음",
                "모의 구매입니다. 금액이 청구되지 않으며 카드 정보도 요구하지 않습니다.",
                "계속하면 Google Play 공식 결제가 열리며 구매 내용을 검토하고 확인할 수 있습니다.",
                "Premium 구매 시뮬레이션", "Google Play에서 계속", "나중에",
                "손전등 아이콘", "테스트 광고",
                "카메라 권한은 플래시를 제어하는 데만 사용됩니다.",
                "일반 끄기 완료. 품위는 그대로입니다.",
                "Premium 끄기: 별 다섯 개짜리 어둠.",
                "테스트 Premium이 활성화되었습니다. 결제는 발생하지 않았습니다.",
                "테스트 Premium을 삭제했습니다. 평민판으로 돌아왔습니다.",
                "Premium이 활성화되었습니다. 어둠에 투자해 주셔서 감사합니다.",
                "이 휴대전화에는 사용 가능한 플래시가 없습니다.",
                "플래시에 접근할 수 없습니다. 카메라 권한을 확인하세요.",
                "카메라가 사용 중입니다. 닫고 다시 시도하세요.",
                "현재 플래시를 사용할 수 없습니다.",
                "현재 Google Play에서 결제를 처리할 수 없습니다.",
                "Premium 상품은 아직 Google Play에서 제공되지 않습니다.",
                "Google Play에서 이 구매에 유효한 혜택을 반환하지 않았습니다.",
                "Google Play 결제를 열 수 없습니다.",
                "구매가 취소되었습니다. 손전등은 이미 꺼져 있습니다.",
                "구매가 완료되지 않았습니다. 다시 시도할 수 있습니다.",
                "결제가 보류 중입니다. 확인되면 Premium이 활성화됩니다.",
                "결제는 도착했지만 확인이 필요합니다. 앱을 다시 여세요.",
                "이 빌드에는 Google Play Billing이 설정되어 있지 않습니다.",
            ),
        )
    }

    private fun catalog(vararg values: String): Map<TextKey, String> {
        require(values.size == TextKey.entries.size) {
            "Expected ${TextKey.entries.size} translations, received ${values.size}."
        }
        return TextKey.entries.zip(values).toMap()
    }
}

class PreferencesLanguageStore(context: Context) {
    private val preferences = context.getSharedPreferences(PREFERENCES_NAME, Context.MODE_PRIVATE)

    fun current(): AppLanguage = AppLanguage.fromCode(
        preferences.getString(KEY_LANGUAGE, null) ?: Locale.getDefault().toLanguageTag(),
    )

    fun save(language: AppLanguage) {
        preferences.edit { putString(KEY_LANGUAGE, language.code) }
    }

    private companion object {
        const val PREFERENCES_NAME = "app_language"
        const val KEY_LANGUAGE = "selected_language"
    }
}
